//spawns mordy

IF
	RandomNumGT(100, 95)
	Global("GmordySp","GLOBAL",0) 
	Global("gBFq15","GLOBAL",1) 
THEN
	RESPONSE #100
		CreateCreature("g_mordyj",[2069.420],3)
		CreateCreature("g_bfcle",[2069.500],3)  
		SetGlobal("GmordySp","GLOBAL",1)
		Continue()
END

IF
	Global("GmordySp","GLOBAL",0) 
	Global("gBFq15","GLOBAL",1) 
THEN
	RESPONSE #100
		CreateCreature("g_mordy",[2069.420],3)
		CreateCreature("g_bfcle",[2069.500],3)  
		SetGlobal("GmordySp","GLOBAL",1)
		Continue()
END
