//spawns Malarite

IF
	Global("GbmalarSp","MYAREA",0)
	Global("gBFq2","GLOBAL",1) 
THEN
		RESPONSE #100
		CreateCreature("gg_malaF",[2536.3256],3)  
		SetGlobal("GbmalarSp","MYAREA",1)
		Continue()
END

//spawns zhent1

IF
	Global("GbzhentSp","MYAREA",0)
	Global("gBFq5","GLOBAL",1) 
THEN
	RESPONSE #100
		CreateCreature("g_Zhent1",[1285.780],3)  
		SetGlobal("GbzhentSp","MYAREA",1)
		Continue()
END
